# Unit 1 - Linear Algebra
### Scalars, Vectors, Matrices, and Tensors

This first project supplements the content covered in unit 1, video 1, "Scalars, Vectors, Matrices, and Tensors".  We will cover the basics of linear algebra and start practicing notation and simple operations. We will be using NumPy, the fundamental package for scientific computing with Python, to create and manipulate arrays. 

### 1. Getting Started With NumPy

To ensure you have the library installed correctly, import NumPy and print the version number using the cell below. 

In [2]:
import sys
import numpy as np

print ('Python: {}'.format(sys.version))
print ('NumPy: {}'.format(np.__version__))

Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
NumPy: 1.17.2


To defining a scalar, which is a single number or value, simply use an equal sign in python.

In [3]:
# a scalar
x = 6
x

6

With NumPy, a vector can be defined using a simple array function.

In [4]:
# a vector
x = np.array((1,2,3))
x

array([1, 2, 3])

NumPy arrays have attributes that can tell us helpful information, such as the shape or size of the vector.

In [5]:
print ('Vector dimensions: {}'.format(x.shape))
print ('Vector size: {}'.format(x.size))
print(x.shape)


Vector dimensions: (3,)
Vector size: 3
(3,)


Defining a matrix is just as easy! Simply use brackets and commas to separate rows. 

In [6]:
x = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
x

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
print ('Matrix dimensions: {}'.format(x.shape))
print ('Matrix size: {}'.format(x.size))
print (x.shape)

Matrix dimensions: (3, 3)
Matrix size: 9
(3, 3)


NumPy makes it easy to quickly define arrays using the desired dimensions. For example, if we wanted to make a 3x3 matrix, we could issue the command in the follow cell:

In [8]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
print ('Matrix dimensions: {}'.format(x.shape))
print ('Matrix size: {}'.format(x.size))

Matrix dimensions: (3, 3)
Matrix size: 9


While it's harder to visualize as the number of axes goes up, it's trivial in NumPy to define a tensor of higher dimensions. For example, a 3-D tensor is created by the following cell. 4-D, 5-D, and 6-D tensors are just as easy to define! 

In [10]:
x = np.ones((3,3,3))
x

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [11]:
print ('Tensor dimensions: {}'.format(x.shape))
print ('Tensor size: {}'.format(x.size))

Tensor dimensions: (3, 3, 3)
Tensor size: 27


### 2. Indexing

Familiarize yourself with NumPy's indexing conventions using the following cells

In [20]:
A = np.ones((5,5), dtype = np.int)
print (A)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [21]:
# indexing starts at 0
A[0,1] = 2
print (A)

[[1 2 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [22]:
# Note! NumPy using rows, columns convention
# assign entire rows or columns using a :
A[:,0] = 3
print (A)

[[3 2 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]
 [3 1 1 1 1]]


In [23]:
A[:,:]=5 #All rows and all colums [:, :]
print(A)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [24]:
# for higher dimensions, simply add an index
A = np.ones((5,5,5), dtype = np.int)

# assign first row a new value
A[:,0,0] = 6
print (A)

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


### 3. Matrix Operations

Let's practice matrix addition, subtraction, and multiplication.

In [25]:
A = np.matrix([[1,2],[3,4]]) # Simple 2x2 matrix
B = np.ones((2,2), dtype = np.int)

In [26]:
print (A)

[[1 2]
 [3 4]]


In [27]:
print (B)

[[1 1]
 [1 1]]


In [29]:
# Element-wise sum
C = A + B
print (C)

[[2 3]
 [4 5]]


In [30]:
# Element-wise subtraction
C = A - B
print (C)

[[0 1]
 [2 3]]


In [31]:
# matrix multiplication
C = A*B
print (C)

[[3 3]
 [7 7]]


### 4. The Matrix Transpose

A transpose is used to flip the rows and columns of an array.  Using NumPy, finding the transpose of a matrix is quick and efficient.

In [43]:
A = np.array(range(9))
A = A.reshape(3,3) #You can reshape a linear array
print (A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [44]:
# calculate tranpose of A
B = A.T
print (B)

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [45]:
# taking the tranpose twice will return the original matrix
C = B.T
print (C)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [46]:
# The transpose will work arrays of any dimension
A = np.array(range(10))
A = A.reshape(2,5)
print (A)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [51]:
# create a column vector by taking the transpose
B = A.T
print ('Matrix A : {}'.format(A))
print ('Transpose of matrix A or B: {}'.format(B))
print ('Matrix  B\'s dimensions: {}'.format(B.shape))
print ('Matrix  A\'s dimensions: {}'.format(A.shape))

Matrix A : [[0 1 2 3 4]
 [5 6 7 8 9]]
Transpose of matrix A or B: [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
Matrix  B's dimensions: (5, 2)
Matrix  A's dimensions: (2, 5)


### 5. Tensors with Higher Dimensions!

While it's very difficult to visualize higher dimensions, NumPy can handle arrays that have any dimensions.  To demonstrate this, create an array with ten dimensions in the cell below.

In [52]:
A = np.ones((3,3,3,3,3,3,3,3,3,3))

In [53]:
print (A.shape)
print(len(A.shape))
print (A.size)

(3, 3, 3, 3, 3, 3, 3, 3, 3, 3)
10
59049
